version: '3.8'

services:
  # Trading bot service
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance-trading-bot
    restart: unless-stopped
    environment:
      - TRADING_MODE=${TRADING_MODE:-paper}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - BINANCE_TESTNET_API_KEY=${BINANCE_TESTNET_API_KEY}
      - BINANCE_TESTNET_API_SECRET=${BINANCE_TESTNET_API_SECRET}
      - MAX_RISK_PER_TRADE=${MAX_RISK_PER_TRADE:-0.005}
      - MAX_DAILY_LOSS=${MAX_DAILY_LOSS:-0.02}
      - MAX_WEEKLY_LOSS=${MAX_WEEKLY_LOSS:-0.05}
      - MIN_CASH_RESERVE=${MIN_CASH_RESERVE:-0.30}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge

