# Hybrid Strategy Configuration (Option-A)
# Combines Grid Trading + DCA with dynamic spread, PnL Gate, and Stop-Loss

# Default policy for all pairs
default_policy:
  # Spread Configuration
  use_dynamic_spread: true
  fixed_spread_pct: 0.5  # Used when dynamic spread is disabled
  
  # Band Thresholds (based on ATR%)
  band_near_threshold: 1.0   # ATR% < 1.0 → near band
  band_mid_threshold: 2.0    # ATR% < 2.0 → mid band, else far band
  
  # Spread by Band
  spread_near_pct: 0.3   # Tight spread for low volatility
  spread_mid_pct: 0.5    # Medium spread for normal volatility
  spread_far_pct: 0.8    # Wide spread for high volatility
  
  # RSI Adjustment
  rsi_adjust_enabled: true
  rsi_adjust_factor: 0.1  # ±10% adjustment based on RSI
  
  # Grid Configuration
  grid_enabled: true
  grid_levels_per_side: 3  # 3 buy + 3 sell levels
  grid_kill_replace_threshold_pct: 1.0  # Recreate grid if price drifts >1%
  grid_min_seconds_between: 300  # 5 minutes cooldown between grid updates
  
  # DCA Configuration
  dca_enabled: true
  dca_rsi_threshold: 35  # Trigger DCA when RSI < 35
  dca_use_ema_gate: true  # Only DCA when price < EMA fast
  dca_cooldown_bars: 5  # Wait 5 bars between DCA orders
  dca_min_distance_from_last_fill_pct: 1.0  # Min 1% distance from last DCA fill
  dca_price_offset_pct: 0.1  # Place DCA order 0.1% below current price
  
  # Take Profit Configuration
  tp_enabled: true
  tp_rsi_threshold: 65  # Trigger TP when RSI > 65
  tp_spread_near_pct: 0.5  # TP spread for near band
  tp_spread_mid_pct: 0.8   # TP spread for mid band
  tp_spread_far_pct: 1.2   # TP spread for far band
  
  # PnL Gate Configuration
  gate_degraded_gap_pct: -3.0      # Enter DEGRADED state at -3% gap
  gate_paused_gap_pct: -5.0        # Enter PAUSED state at -5% gap
  gate_degraded_daily_pnl_pct: -2.0  # Enter DEGRADED at -2% daily PnL
  gate_paused_daily_pnl_pct: -4.0    # Enter PAUSED at -4% daily PnL
  
  # Stop-Loss Configuration
  hard_stop_daily_pnl_pct: -5.0  # Hard stop at -5% daily PnL
  hard_stop_gap_pct: -8.0        # Hard stop at -8% gap
  
  # Auto-Resume Configuration (after hard stop)
  auto_resume_enabled: true      # Enable auto-resume after hard stop
  resume_rsi_threshold: 40       # Resume when RSI > 40 (oversold recovery)
  resume_price_recovery_pct: 2.0 # Resume when price recovers 2% from stop price
  resume_cooldown_bars: 60       # Wait 60 bars (60 min for 1m) after stop before checking resume
  
  # Timeframe
  bar_timeframe: "1m"  # 1-minute bars

# Pair-specific overrides
pairs:
  BTCUSDT:
    # BTC typically has lower volatility
    spread_near_pct: 0.2
    spread_mid_pct: 0.4
    spread_far_pct: 0.6
    grid_levels_per_side: 4
    dca_rsi_threshold: 30
  
  ETHUSDT:
    # ETH similar to BTC
    spread_near_pct: 0.25
    spread_mid_pct: 0.45
    spread_far_pct: 0.7
    grid_levels_per_side: 4
  
  SOLUSDT:
    # SOL more volatile
    spread_near_pct: 0.4
    spread_mid_pct: 0.6
    spread_far_pct: 1.0
    grid_levels_per_side: 3
    dca_rsi_threshold: 35
  
  # Add more pairs as needed

# Risk Management
risk:
  max_position_size_pct: 20.0  # Max 20% of capital per position
  max_total_exposure_pct: 80.0  # Max 80% total exposure
  min_cash_reserve_pct: 20.0    # Keep min 20% cash

# Order Execution
execution:
  max_orders_per_symbol: 10  # Max 10 pending orders per symbol
  min_order_value_usdt: 11.0  # Min $11 per order (Binance minimum)
  use_post_only: true  # Use post-only orders for grid
  retry_on_fail: true
  max_retries: 3

# Logging
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  log_orders: true
  log_fills: true
  log_pnl_updates: true

