# Trading Strategies Configuration

strategies:
  # DCA Strategy
  dca:
    enabled: false
    capital_allocation: 0.35  # 35% of capital
    max_layers: 4
    layer_drop_pct: [5, 8, 12, 18]  # % price drops to add layers
    tp_ladder_pct: [5, 8, 12]  # % gains for take profit
    catastrophic_sl_pct: 20  # % loss to exit all
    time_based: false
    interval_days: 7
  
  # Trend Following Strategy
  trend_following:
    enabled: true
    capital_allocation: 0.30  # 30% of capital
    ma_fast: 20
    ma_slow: 50
    adx_threshold: 25
    atr_multiplier: 2.0
    risk_reward_ratio: 2.0
    entry_method: ma_cross  # ma_cross, donchian, rsi_pullback
    rsi_period: 14
    rsi_oversold: 40
    rsi_overbought: 60
  
  # Mean Reversion Strategy
  mean_reversion:
    enabled: true
    capital_allocation: 0.20  # 20% of capital
    rsi_period: 14
    rsi_oversold: 30
    rsi_overbought: 70
    bb_period: 20
    bb_std: 2.0
    adx_max: 20  # Maximum ADX for ranging market
    atr_multiplier: 1.5
    entry_method: combined  # rsi, bollinger, combined
  
  # Grid Strategy
  grid:
    enabled: true
    capital_allocation: 0.15  # 15% of capital
    num_grids: 10
    grid_spacing_pct: 1.0  # % spacing between grids
    tp_per_grid: 0.5  # % profit per grid
    range_period: 50
    bb_period: 20
    bb_std: 2.0
    max_buy_orders: 5
    catastrophic_sl_pct: 10

